version: '3.8'

services:
  nodejs_app:
    container_name: nodejs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - basileia_production_mongo

  basileia_production_mongo:
    container_name: basileia_production_mongo
    image: mongo
    ports:
      - "27177:27177"  # Map MongoDB port 27177 of the container to host port 27177
    environment:
      - MONGO_INITDB_DATABASE=BasileiaProd
    env_file:
      - .env

  basileia_production_mongo_express:
    container_name: basileia_production_mongo_express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=syscoadmin
      - ME_CONFIG_BASICAUTH_PASSWORD=E7Dw~e5NKh4Ly's
    depends_on:
      - basileia_production_mongo
