version: '3.8'

services:
  nodejs_app:
    container_name: nodejs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - basileia_production_mongo

  basileia_production_mongo:
    container_name: basileia_production_mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/basileia_persistent/mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    env_file:
      - .env


