version: '3.9'
services:
  backend:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: onnow-server
    networks:
      - onnow-network
    volumes:
      - ./:/app
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://syscoadmin:E7Dw~e5NKh4Ly's@mongo:27017/OnnowProd?authSource=admin
    depends_on:
      - mongo
  mongo:
    container_name: onnnow-db
    image: mongo
    ports:
      - 27177:27017
    networks:
      - onnow-network
    volumes:
      - mongoData:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: syscoadmin
      MONGO_INITDB_ROOT_PASSWORD: E7Dw~e5NKh4Ly's
      MONGO_INITDB_DATABASE: OnnowProd
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - onnow-network
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: syscodbadmin
      ME_CONFIG_BASICAUTH_PASSWORD: VNY*\:u@n{x7<?2
      ME_CONFIG_MONGODB_ADMINUSERNAME: sysco
      ME_CONFIG_MONGODB_ADMINPASSWORD: E7Dw~e5NKh4Ly's
      ME_CONFIG_MONGODB_URL: mongodb://syscoadmin:E7Dw~e5NKh4Ly's@mongo:27017
    depends_on:
      - mongo
networks:
  onnow-network:
volumes:
  mongoData: